const countries = [
                        { name: "Afghanistan", url: "https://mfa.gov.af/en/", flag: "https://www.cia.gov/the-world-factbook/static/2b3a06ae2c0b517dbfe6629f1f967718/1be8f/AF-flag.webp" },
            { name: "Albania", url: "https://punetejashtme.gov.al/en", flag: "https://upload.wikimedia.org/wikipedia/commons/3/36/Flag_of_Albania.svg" },
            { name: "Algeria", url: "https://www.mfa.gov.dz/", flag: "https://upload.wikimedia.org/wikipedia/commons/7/77/Flag_of_Algeria.svg" },
            { name: "Andorra", url: "https://www.exteriors.ad/", flag: "https://upload.wikimedia.org/wikipedia/commons/1/19/Flag_of_Andorra.svg" },
            { name: "Angola", url: "https://mirex.gov.ao/", flag: "https://upload.wikimedia.org/wikipedia/commons/9/9d/Flag_of_Angola.svg" },
            { name: "Argentina", url: "https://cancilleria.gob.ar/en/services/visas", flag: "https://upload.wikimedia.org/wikipedia/commons/1/1a/Flag_of_Argentina.svg" },
            { name: "Armenia", url: "https://www.mfa.am/en/visa/", flag: "https://upload.wikimedia.org/wikipedia/commons/2/2f/Flag_of_Armenia.svg" },
            { name: "Australia", url: "https://immi.homeaffairs.gov.au/visas", flag: "https://upload.wikimedia.org/wikipedia/commons/b/b9/Flag_of_Australia.svg" },
            { name: "Austria", url: "https://www.bmeia.gv.at/en/", flag: "https://upload.wikimedia.org/wikipedia/commons/4/41/Flag_of_Austria.svg" },
            { name: "Azerbaijan", url: "https://mfa.gov.az/en/category/visa", flag: "https://upload.wikimedia.org/wikipedia/commons/d/dd/Flag_of_Azerbaijan.svg" },
            { name: "Bahamas", url: "https://mofa.gov.bs/", flag: "https://upload.wikimedia.org/wikipedia/commons/9/93/Flag_of_the_Bahamas.svg" },
            { name: "Bahrain", url: "https://www.npra.gov.bh/en/", flag: "https://upload.wikimedia.org/wikipedia/commons/2/2c/Flag_of_Bahrain.svg" },
            { name: "Bangladesh", url: "https://www.visa.gov.bd/", flag: "https://upload.wikimedia.org/wikipedia/commons/f/f9/Flag_of_Bangladesh.svg" },
            { name: "Barbados", url: "https://www.immigration.gov.bb/", flag: "https://upload.wikimedia.org/wikipedia/commons/e/ef/Flag_of_Barbados.svg" },
            { name: "Belarus", url: "https://mfa.gov.by/en/visa/", flag: "https://upload.wikimedia.org/wikipedia/commons/8/85/Flag_of_Belarus.svg" },
            { name: "Belgium", url: "https://diplomatie.belgium.be/en", flag: "https://upload.wikimedia.org/wikipedia/commons/6/65/Flag_of_Belgium.svg" },
            { name: "Belize", url: "https://www.mfa.gov.bz/", flag: "https://upload.wikimedia.org/wikipedia/commons/e/e7/Flag_of_Belize.svg" },
            { name: "Benin", url: "https://diplomatie.gouv.bj/", flag: "https://upload.wikimedia.org/wikipedia/commons/0/0a/Flag_of_Benin.svg" },
            { name: "Bhutan", url: "https://www.mfa.gov.bt/", flag: "https://upload.wikimedia.org/wikipedia/commons/9/91/Flag_of_Bhutan.svg" },
            { name: "Bolivia", url: "http://www.rree.gob.bo/", flag: "https://upload.wikimedia.org/wikipedia/commons/4/48/Flag_of_Bolivia.svg" },
            { name: "Bosnia and Herzegovina", url: "http://www.mvp.gov.ba/", flag: "https://upload.wikimedia.org/wikipedia/commons/b/bf/Flag_of_Bosnia_and_Herzegovina.svg" },
            { name: "Botswana", url: "http://www.gov.bw/en/Ministries--Authorities/Ministries/Ministry-of-Nationality-Immigration-and-Gender-Affairs/", flag: "https://upload.wikimedia.org/wikipedia/commons/f/fa/Flag_of_Botswana.svg" },
            { name: "Brazil", url: "http://www.itamaraty.gov.br/en/", flag: "https://upload.wikimedia.org/wikipedia/en/0/05/Flag_of_Brazil.svg" },
            { name: "Brunei", url: "http://www.mfa.gov.bn/Pages/home.aspx", flag: "https://upload.wikimedia.org/wikipedia/commons/9/9c/Flag_of_Brunei.svg" },
            { name: "Bulgaria", url: "https://www.mfa.bg/en/services-travel/consular-services/visas", flag: "https://upload.wikimedia.org/wikipedia/commons/9/9a/Flag_of_Bulgaria.svg" },
            { name: "Burkina Faso", url: "https://www.mae.gov.bf/", flag: "https://upload.wikimedia.org/wikipedia/commons/3/31/Flag_of_Burkina_Faso.svg" },
            { name: "Burundi", url: "https://www.mae.gov.bi/", flag: "https://upload.wikimedia.org/wikipedia/commons/5/50/Flag_of_Burundi.svg" },
            { name: "Cabo Verde", url: "https://www.governo.cv/", flag: "https://upload.wikimedia.org/wikipedia/commons/3/38/Flag_of_Cape_Verde.svg" },
            { name: "Cambodia", url: "https://www.mfaic.gov.kh/", flag: "https://upload.wikimedia.org/wikipedia/commons/8/83/Flag_of_Cambodia.svg" },
            { name: "Cameroon", url: "https://www.diplocam.cm/", flag: "https://upload.wikimedia.org/wikipedia/commons/4/4f/Flag_of_Cameroon.svg" },
            { name: "Canada", url: "https://www.canada.ca/en/immigration-refugees-citizenship.html", flag: "https://upload.wikimedia.org/wikipedia/commons/d/d9/Flag_of_Canada_%28Pantone%29.svg" },
            { name: "Chad", url: "http://diplomatie-gouv.td/", flag: "https://upload.wikimedia.org/wikipedia/commons/4/4b/Flag_of_Chad.svg" },
            { name: "Chile", url: "https://chile.gob.cl/", flag: "https://upload.wikimedia.org/wikipedia/commons/7/78/Flag_of_Chile.svg" },
            { name: "China", url: "https://www.nia.gov.cn/", flag: "https://upload.wikimedia.org/wikipedia/commons/f/fa/Flag_of_the_People%27s_Republic_of_China.svg" },
            { name: "Colombia", url: "https://www.cancilleria.gov.co/", flag: "https://upload.wikimedia.org/wikipedia/commons/2/21/Flag_of_Colombia.svg" },
            { name: "Comoros", url: "http://www.diplomatie.gouv.km/", flag: "https://upload.wikimedia.org/wikipedia/commons/9/94/Flag_of_the_Comoros.svg" },
            { name: "Congo", url: "https://drc-covid19.com/", flag: "https://upload.wikimedia.org/wikipedia/commons/6/6f/Flag_of_the_Democratic_Republic_of_the_Congo.svg" },
            { name: "Costa Rica", url: "https://www.rree.go.cr/", flag: "https://upload.wikimedia.org/wikipedia/commons/b/bc/Flag_of_Costa_Rica_%28state%29.svg" },
            { name: "Croatia", url: "http://www.mvep.hr/en/", flag: "https://upload.wikimedia.org/wikipedia/commons/1/1b/Flag_of_Croatia.svg" },
            { name: "Cuba", url: "http://www.cubaminrex.cu/", flag: "https://upload.wikimedia.org/wikipedia/commons/b/bd/Flag_of_Cuba.svg" },
            { name: "Cyprus", url: "http://www.mfa.gov.cy/", flag: "https://upload.wikimedia.org/wikipedia/commons/d/d4/Flag_of_Cyprus.svg" },
            { name: "Czech Republic", url: "https://www.mzv.cz/jnp/en/information_for_aliens/index.html", flag: "https://upload.wikimedia.org/wikipedia/commons/c/cb/Flag_of_the_Czech_Republic.svg" },
            { name: "Denmark", url: "http://um.dk/en/travel-and-residence/", flag: "https://upload.wikimedia.org/wikipedia/commons/9/9c/Flag_of_Denmark.svg" },
            { name: "Djibouti", url: "https://www.presidence.dj/", flag: "https://upload.wikimedia.org/wikipedia/commons/3/34/Flag_of_Djibouti.svg" },
            { name: "Dominica", url: "https://foreignaffairs.gov.dm/", flag: "https://upload.wikimedia.org/wikipedia/commons/c/c4/Flag_of_Dominica.svg" },
            { name: "Dominican Republic", url: "https://www.mirex.gob.do/", flag: "https://upload.wikimedia.org/wikipedia/commons/9/9f/Flag_of_the_Dominican_Republic.svg" },
            { name: "Ecuador", url: "https://www.cancilleria.gob.ec/", flag: "https://upload.wikimedia.org/wikipedia/commons/e/e8/Flag_of_Ecuador.svg" },
            { name: "Egypt", url: "https://www.mfa.gov.eg/", flag: "https://upload.wikimedia.org/wikipedia/commons/f/fe/Flag_of_Egypt.svg" },
            { name: "El Salvador", url: "http://rree.gob.sv/", flag: "https://upload.wikimedia.org/wikipedia/commons/3/34/Flag_of_El_Salvador.svg" },
            { name: "Equatorial Guinea", url: "https://www.guineaecuatorialpress.com/", flag: "https://upload.wikimedia.org/wikipedia/commons/3/31/Flag_of_Equatorial_Guinea.svg" },
            { name: "Eritrea", url: "http://www.shabait.com/", flag: "https://upload.wikimedia.org/wikipedia/commons/2/29/Flag_of_Eritrea.svg" },
            { name: "Estonia", url: "https://vm.ee/en", flag: "https://upload.wikimedia.org/wikipedia/commons/8/8f/Flag_of_Estonia.svg" },
            { name: "Eswatini", url: "http://www.gov.sz/", flag: "https://upload.wikimedia.org/wikipedia/commons/f/fb/Flag_of_Eswatini.svg" },
            { name: "Ethiopia", url: "https://www.mfa.gov.et/", flag: "https://upload.wikimedia.org/wikipedia/commons/7/71/Flag_of_Ethiopia.svg" },
            { name: "Fiji", url: "http://www.immigration.gov.fj/", flag: "https://upload.wikimedia.org/wikipedia/commons/b/ba/Flag_of_Fiji.svg" },
            { name: "Finland", url: "https://um.fi/frontpage", flag: "https://upload.wikimedia.org/wikipedia/commons/b/bc/Flag_of_Finland.svg" },
            { name: "France", url: "https://www.diplomatie.gouv.fr/en/", flag: "https://upload.wikimedia.org/wikipedia/en/c/c3/Flag_of_France.svg" },
            { name: "Gabon", url: "https://www.diplomatie.gouv.ga/", flag: "https://upload.wikimedia.org/wikipedia/commons/0/04/Flag_of_Gabon.svg" },
            { name: "Gambia", url: "http://www.mofa.gov.gm/", flag: "https://upload.wikimedia.org/wikipedia/commons/7/77/Flag_of_The_Gambia.svg" },
            { name: "Georgia", url: "https://mfa.gov.ge/", flag: "https://upload.wikimedia.org/wikipedia/commons/0/0f/Flag_of_Georgia.svg" },
            { name: "Germany", url: "https://www.auswaertiges-amt.de/en", flag: "https://upload.wikimedia.org/wikipedia/en/b/ba/Flag_of_Germany.svg" },
            { name: "Ghana", url: "https://www.mfa.gov.gh/", flag: "https://upload.wikimedia.org/wikipedia/commons/1/19/Flag_of_Ghana.svg" },
            { name: "Greece", url: "https://www.mfa.gr/en/", flag: "https://upload.wikimedia.org/wikipedia/commons/5/5c/Flag_of_Greece.svg" },
            { name: "Grenada", url: "https://www.gov.gd/", flag: "https://upload.wikimedia.org/wikipedia/commons/b/bc/Flag_of_Grenada.svg" },
            { name: "Guatemala", url: "http://www.minex.gob.gt/", flag: "https://upload.wikimedia.org/wikipedia/commons/e/ec/Flag_of_Guatemala.svg" },
            { name: "Guinea", url: "http://www.mae.gov.gn/", flag: "https://upload.wikimedia.org/wikipedia/commons/e/ed/Flag_of_Guinea.svg" },
            { name: "Guinea-Bissau", url: "http://www.ministeriodes.org/", flag: "https://upload.wikimedia.org/wikipedia/commons/0/01/Flag_of_Guinea-Bissau.svg" },
            { name: "Guyana", url: "http://www.minfor.gov.gy/", flag: "https://upload.wikimedia.org/wikipedia/commons/9/99/Flag_of_Guyana.svg" },
            { name: "Haiti", url: "https://www.mae.gouv.ht/", flag: "https://upload.wikimedia.org/wikipedia/commons/5/56/Flag_of_Haiti.svg" },
            { name: "Honduras", url: "http://www.sre.gob.hn/", flag: "https://upload.wikimedia.org/wikipedia/commons/8/82/Flag_of_Honduras.svg" },
            { name: "Hungary", url: "https://konzuliszolgalat.kormany.hu/en", flag: "https://upload.wikimedia.org/wikipedia/commons/c/c1/Flag_of_Hungary.svg" },
            { name: "Iceland", url: "https://www.government.is/ministries/ministry-for-foreign-affairs/", flag: "https://upload.wikimedia.org/wikipedia/commons/c/ce/Flag_of_Iceland.svg" },
            { name: "India", url: "https://indianvisaonline.gov.in/", flag: "https://upload.wikimedia.org/wikipedia/en/4/41/Flag_of_India.svg" },
            { name: "Indonesia", url: "https://kemlu.go.id/", flag: "https://upload.wikimedia.org/wikipedia/commons/9/9f/Flag_of_Indonesia.svg" },
            { name: "Iran", url: "https://en.mfa.ir/", flag: "https://upload.wikimedia.org/wikipedia/commons/c/ca/Flag_of_Iran.svg" },
            { name: "Iraq", url: "http://www.mofa.gov.iq/en/", flag: "https://upload.wikimedia.org/wikipedia/commons/f/f6/Flag_of_Iraq.svg" },
            { name: "Ireland", url: "https://www.dfa.ie/", flag: "https://upload.wikimedia.org/wikipedia/commons/4/45/Flag_of_Ireland.svg" },
            { name: "Israel", url: "https://mfa.gov.il/", flag: "https://upload.wikimedia.org/wikipedia/commons/d/d4/Flag_of_Israel.svg" },
            { name: "Italy", url: "https://www.esteri.it/mae/en/", flag: "https://upload.wikimedia.org/wikipedia/en/0/03/Flag_of_Italy.svg" },
            { name: "Jamaica", url: "https://mfaft.gov.jm/", flag: "https://upload.wikimedia.org/wikipedia/commons/0/0a/Flag_of_Jamaica.svg" },
            { name: "Japan", url: "https://www.mofa.go.jp/j_info/visit/visa/index.html", flag: "https://upload.wikimedia.org/wikipedia/en/9/9e/Flag_of_Japan.svg" },
             { name: "Jordan", url: "https://mfa.gov.jo/", flag: "https://upload.wikimedia.org/wikipedia/commons/c/c0/Flag_of_Jordan.svg" },
            { name: "Kazakhstan", url: "https://www.gov.kz/memleket/entities/mfa?lang=en", flag: "https://upload.wikimedia.org/wikipedia/commons/d/d3/Flag_of_Kazakhstan.svg" },
            { name: "Kenya", url: "https://www.mfa.go.ke/", flag: "https://upload.wikimedia.org/wikipedia/commons/4/49/Flag_of_Kenya.svg" },
            { name: "Kiribati", url: "https://www.mfa.gov.ki/", flag: "https://upload.wikimedia.org/wikipedia/commons/d/d3/Flag_of_Kiribati.svg" },
            { name: "Kuwait", url: "https://www.mofa.gov.kw/", flag: "https://upload.wikimedia.org/wikipedia/commons/a/aa/Flag_of_Kuwait.svg" },
            { name: "Kyrgyzstan", url: "http://mfa.gov.kg/", flag: "https://upload.wikimedia.org/wikipedia/commons/c/c7/Flag_of_Kyrgyzstan.svg" },
            { name: "Laos", url: "http://www.mofa.gov.la/", flag: "https://upload.wikimedia.org/wikipedia/commons/5/56/Flag_of_Laos.svg" },
            { name: "Latvia", url: "https://www.mfa.gov.lv/en", flag: "https://upload.wikimedia.org/wikipedia/commons/8/84/Flag_of_Latvia.svg" },
            { name: "Lebanon", url: "http://www.mfa.gov.lb/", flag: "https://upload.wikimedia.org/wikipedia/commons/5/59/Flag_of_Lebanon.svg" },
            { name: "Lesotho", url: "http://www.foreign.gov.ls/", flag: "https://upload.wikimedia.org/wikipedia/commons/4/4a/Flag_of_Lesotho.svg" },
            { name: "Liberia", url: "http://www.mofa.gov.lr/", flag: "https://upload.wikimedia.org/wikipedia/commons/b/b8/Flag_of_Liberia.svg" },
            { name: "Libya", url: "http://www.foreign.gov.ly/", flag: "https://upload.wikimedia.org/wikipedia/commons/0/05/Flag_of_Libya.svg" },
            { name: "Liechtenstein", url: "https://www.regierung.li/", flag: "https://upload.wikimedia.org/wikipedia/commons/4/47/Flag_of_Liechtenstein.svg" },
            { name: "Lithuania", url: "https://urm.lt/default/en/", flag: "https://upload.wikimedia.org/wikipedia/commons/1/11/Flag_of_Lithuania.svg" },
            { name: "Luxembourg", url: "https://maee.gouvernement.lu/en.html", flag: "https://upload.wikimedia.org/wikipedia/commons/d/da/Flag_of_Luxembourg.svg" },
            { name: "Madagascar", url: "http://www.diplomatie.gov.mg/", flag: "https://upload.wikimedia.org/wikipedia/commons/b/bc/Flag_of_Madagascar.svg" },
            { name: "Malawi", url: "https://www.foreignaffairs.gov.mw/", flag: "https://upload.wikimedia.org/wikipedia/commons/d/d1/Flag_of_Malawi.svg" },
            { name: "Malaysia", url: "https://www.imi.gov.my/", flag: "https://upload.wikimedia.org/wikipedia/commons/6/66/Flag_of_Malaysia.svg" },
            { name: "Maldives", url: "https://www.foreign.gov.mv/", flag: "https://upload.wikimedia.org/wikipedia/commons/0/0f/Flag_of_Maldives.svg" },
            { name: "Mali", url: "https://www.diplomatie.ml/", flag: "https://upload.wikimedia.org/wikipedia/commons/9/92/Flag_of_Mali.svg" },
            { name: "Malta", url: "https://foreignaffairs.gov.mt/en/Pages/Index.aspx", flag: "https://upload.wikimedia.org/wikipedia/commons/7/73/Flag_of_Malta.svg" },
            { name: "Marshall Islands", url: "https://www.rmiembassyus.org/", flag: "https://upload.wikimedia.org/wikipedia/commons/2/2e/Flag_of_the_Marshall_Islands.svg" },
            { name: "Mauritania", url: "https://www.diplomatie.gov.mr/", flag: "https://upload.wikimedia.org/wikipedia/commons/4/43/Flag_of_Mauritania.svg" },
            { name: "Mauritius", url: "http://foreign.govmu.org/English/Pages/default.aspx", flag: "https://upload.wikimedia.org/wikipedia/commons/7/77/Flag_of_Mauritius.svg" },
            { name: "Mexico", url: "https://www.gob.mx/sre", flag: "https://upload.wikimedia.org/wikipedia/commons/f/fc/Flag_of_Mexico.svg" },
            { name: "Micronesia", url: "http://www.fsmpio.fm/", flag: "https://upload.wikimedia.org/wikipedia/commons/e/e4/Flag_of_the_Federated_States_of_Micronesia.svg" },
            { name: "Moldova", url: "https://mfa.gov.md/en", flag: "https://upload.wikimedia.org/wikipedia/commons/2/27/Flag_of_Moldova.svg" },
            { name: "Monaco", url: "https://en.gouv.mc/Government-Institutions/The-Government/Ministry-of-Foreign-Affairs-and-Cooperation", flag: "https://upload.wikimedia.org/wikipedia/commons/e/ea/Flag_of_Monaco.svg" },
            { name: "Mongolia", url: "https://mfa.gov.mn/en/", flag: "https://upload.wikimedia.org/wikipedia/commons/4/4c/Flag_of_Mongolia.svg" },
            { name: "Montenegro", url: "http://www.mvp.gov.me/en/ministry", flag: "https://upload.wikimedia.org/wikipedia/commons/6/64/Flag_of_Montenegro.svg" },
            { name: "Morocco", url: "http://www.diplomatie.ma/en/", flag: "https://upload.wikimedia.org/wikipedia/commons/2/2c/Flag_of_Morocco.svg" },
            { name: "Mozambique", url: "https://www.minec.gov.mz/", flag: "https://upload.wikimedia.org/wikipedia/commons/d/d0/Flag_of_Mozambique.svg" },
            { name: "Namibia", url: "http://www.mirco.gov.na/", flag: "https://upload.wikimedia.org/wikipedia/commons/0/00/Flag_of_Namibia.svg" },
            { name: "Nauru", url: "http://www.naurugov.nr/government/departments/department-of-foreign-affairs-and-trade.aspx", flag: "https://upload.wikimedia.org/wikipedia/commons/3/30/Flag_of_Nauru.svg" },
            { name: "Nepal", url: "http://www.nepalimmigration.gov.np/", flag: "https://upload.wikimedia.org/wikipedia/commons/9/9b/Flag_of_Nepal.svg" },
            { name: "Netherlands", url: "https://www.government.nl/ministries/ministry-of-foreign-affairs", flag: "https://upload.wikimedia.org/wikipedia/commons/2/20/Flag_of_the_Netherlands.svg" },
            { name: "New Zealand", url: "https://www.immigration.govt.nz/new-zealand-visas", flag: "https://upload.wikimedia.org/wikipedia/commons/3/3e/Flag_of_New_Zealand.svg" },
            { name: "Nicaragua", url: "https://www.cancilleria.gob.ni/", flag: "https://upload.wikimedia.org/wikipedia/commons/1/19/Flag_of_Nicaragua.svg" },
            { name: "Niger", url: "https://www.gouv.ne/", flag: "https://upload.wikimedia.org/wikipedia/commons/f/f4/Flag_of_Niger.svg" },
            { name: "Nigeria", url: "https://portal.immigration.gov.ng/", flag: "https://upload.wikimedia.org/wikipedia/commons/7/79/Flag_of_Nigeria.svg" },
            { name: "North Macedonia", url: "http://www.mfa.gov.mk/", flag: "https://upload.wikimedia.org/wikipedia/commons/7/79/Flag_of_North_Macedonia.svg" },
            { name: "Norway", url: "https://www.udi.no/en/", flag: "https://upload.wikimedia.org/wikipedia/commons/d/d9/Flag_of_Norway.svg" },
            { name: "Oman", url: "https://www.rop.gov.om/english/dg_pr_visaservices.html", flag: "https://upload.wikimedia.org/wikipedia/commons/d/dd/Flag_of_Oman.svg" },
            { name: "Pakistan", url: "https://visa.nadra.gov.pk/", flag: "https://upload.wikimedia.org/wikipedia/commons/3/32/Flag_of_Pakistan.svg" },
            { name: "Palau", url: "https://www.palauembassy.com/", flag: "https://upload.wikimedia.org/wikipedia/commons/4/48/Flag_of_Palau.svg" },
            { name: "Panama", url: "https://www.migracion.gob.pa/", flag: "https://upload.wikimedia.org/wikipedia/commons/a/ab/Flag_of_Panama.svg" },
            { name: "Papua New Guinea", url: "http://ica.gov.pg/", flag: "https://upload.wikimedia.org/wikipedia/commons/e/e3/Flag_of_Papua_New_Guinea.svg" },
            { name: "Paraguay", url: "https://www.mre.gov.py/", flag: "https://upload.wikimedia.org/wikipedia/commons/2/27/Flag_of_Paraguay.svg" },
            { name: "Peru", url: "https://www.gob.pe/rree", flag: "https://upload.wikimedia.org/wikipedia/commons/c/cf/Flag_of_Peru.svg" },
            { name: "Philippines", url: "https://www.dfa.gov.ph/", flag: "https://upload.wikimedia.org/wikipedia/commons/9/99/Flag_of_the_Philippines.svg" },
            { name: "Poland", url: "https://www.gov.pl/web/diplomacy", flag: "https://upload.wikimedia.org/wikipedia/en/1/12/Flag_of_Poland.svg" },
            { name: "Portugal", url: "https://www.portugal.gov.pt/en/gc21/ministries/foreign-affairs", flag: "https://upload.wikimedia.org/wikipedia/commons/5/5c/Flag_of_Portugal.svg" },
            { name: "Qatar", url: "https://portal.moi.gov.qa/wps/portal/MOIInternet/services/inquiries/visa-services", flag: "https://upload.wikimedia.org/wikipedia/commons/6/65/Flag_of_Qatar.svg" },
            { name: "Romania", url: "https://www.mae.ro/en", flag: "https://upload.wikimedia.org/wikipedia/commons/7/73/Flag_of_Romania.svg" },
            { name: "Russia", url: "http://www.mid.ru/en/main_en", flag: "https://upload.wikimedia.org/wikipedia/en/f/f3/Flag_of_Russia.svg" },
            { name: "Rwanda", url: "https://www.migration.gov.rw/", flag: "https://upload.wikimedia.org/wikipedia/commons/1/17/Flag_of_Rwanda.svg" },
            { name: "Saint Kitts and Nevis", url: "http://www.foreign.gov.kn/", flag: "https://upload.wikimedia.org/wikipedia/commons/f/fe/Flag_of_Saint_Kitts_and_Nevis.svg" },
            { name: "Saint Lucia", url: "http://www.govt.lc/ministries/external-affairs", flag: "https://upload.wikimedia.org/wikipedia/commons/9/9f/Flag_of_Saint_Lucia.svg" },
            { name: "Saint Vincent and the Grenadines", url: "http://foreign.gov.vc/foreign/", flag: "https://upload.wikimedia.org/wikipedia/commons/6/6d/Flag_of_Saint_Vincent_and_the_Grenadines.svg" },
            { name: "Samoa", url: "http://www.samoagovt.ws/ministries/mpmc/", flag: "https://upload.wikimedia.org/wikipedia/commons/3/31/Flag_of_Samoa.svg" },
            { name: "San Marino", url: "http://www.esteri.sm/on-line/en/home.html", flag: "https://upload.wikimedia.org/wikipedia/commons/b/b1/Flag_of_San_Marino.svg" },
            { name: "Sao Tome and Principe", url: "http://www.mne.gov.st/", flag: "https://upload.wikimedia.org/wikipedia/commons/0/0a/Flag_of_S%C3%A3o_Tom%C3%A9_and_Pr%C3%ADncipe.svg" },
            { name: "Saudi Arabia", url: "https://www.mofa.gov.sa/", flag: "https://upload.wikimedia.org/wikipedia/commons/0/0d/Flag_of_Saudi_Arabia.svg" },
            { name: "Senegal", url: "http://www.diplomatie.gouv.sn/", flag: "https://upload.wikimedia.org/wikipedia/commons/f/fd/Flag_of_Senegal.svg" },
            { name: "Serbia", url: "http://www.mfa.gov.rs/en/", flag: "https://upload.wikimedia.org/wikipedia/commons/f/ff/Flag_of_Serbia.svg" },
            { name: "Seychelles", url: "http://www.mfa.gov.sc/", flag: "https://upload.wikimedia.org/wikipedia/commons/f/fc/Flag_of_Seychelles.svg" },
            { name: "Sierra Leone", url: "https://www.foreignaffairs.gov.sl/", flag: "https://upload.wikimedia.org/wikipedia/commons/1/17/Flag_of_Sierra_Leone.svg" },
            { name: "Singapore", url: "https://www.ica.gov.sg/", flag: "https://upload.wikimedia.org/wikipedia/commons/4/48/Flag_of_Singapore.svg" },
            { name: "Slovakia", url: "https://www.mzv.sk/web/en", flag: "https://upload.wikimedia.org/wikipedia/commons/e/e6/Flag_of_Slovakia.svg" },
            { name: "Slovenia", url: "http://www.mzz.gov.si/en/", flag: "https://upload.wikimedia.org/wikipedia/commons/f/f0/Flag_of_Slovenia.svg" },
            { name: "Solomon Islands", url: "http://www.mfaet.gov.sb/", flag: "https://upload.wikimedia.org/wikipedia/commons/7/74/Flag_of_the_Solomon_Islands.svg" },
            { name: "Somalia", url: "https://www.mfa.gov.so/", flag: "https://upload.wikimedia.org/wikipedia/commons/a/a0/Flag_of_Somalia.svg" },
            { name: "South Africa", url: "http://www.dha.gov.za/", flag: "https://upload.wikimedia.org/wikipedia/commons/a/af/Flag_of_South_Africa.svg" },
            { name: "South Sudan", url: "https://mfa.gov.ss/", flag: "https://upload.wikimedia.org/wikipedia/commons/7/7a/Flag_of_South_Sudan.svg" },
            { name: "Spain", url: "http://www.exteriores.gob.es/Portal/en/Paginas/inicio.aspx", flag: "https://upload.wikimedia.org/wikipedia/en/9/9a/Flag_of_Spain.svg" },
            { name: "Sri Lanka", url: "http://www.immigration.gov.lk/", flag: "https://upload.wikimedia.org/wikipedia/commons/1/11/Flag_of_Sri_Lanka.svg" },
            { name: "Sudan", url: "http://www.mfa.gov.sd/", flag: "https://upload.wikimedia.org/wikipedia/commons/0/01/Flag_of_Sudan.svg" },
            { name: "Suriname", url: "http://www.gov.sr/ministry-of-foreign-affairs.aspx", flag: "https://upload.wikimedia.org/wikipedia/commons/6/60/Flag_of_Suriname.svg" },
            { name: "Sweden", url: "https://www.migrationsverket.se/", flag: "https://upload.wikimedia.org/wikipedia/en/4/4c/Flag_of_Sweden.svg" },
            { name: "Switzerland", url: "https://www.sem.admin.ch/sem/en/home.html", flag: "https://upload.wikimedia.org/wikipedia/commons/f/f3/Flag_of_Switzerland.svg" },
            { name: "Syria", url: "https://www.mofa.gov.sy/", flag: "https://upload.wikimedia.org/wikipedia/commons/5/53/Flag_of_Syria.svg" },
            { name: "Taiwan", url: "https://www.boca.gov.tw/", flag: "https://upload.wikimedia.org/wikipedia/commons/7/72/Flag_of_the_Republic_of_China.svg" },
            { name: "Tajikistan", url: "https://mfa.tj/", flag: "https://upload.wikimedia.org/wikipedia/commons/d/d0/Flag_of_Tajikistan.svg" },
            { name: "Tanzania", url: "https://www.foreign.go.tz/", flag: "https://upload.wikimedia.org/wikipedia/commons/3/38/Flag_of_Tanzania.svg" },
            { name: "Thailand", url: "http://www.mfa.go.th", flag: "https://upload.wikimedia.org/wikipedia/commons/a/a9/Flag_of_Thailand.svg" },
            { name: "Timor-Leste", url: "http://www.mfac.gov.tl/en/", flag: "https://upload.wikimedia.org/wikipedia/commons/2/26/Flag_of_East_Timor.svg" },
            { name: "Togo", url: "https://diplomatie.gouv.tg/", flag: "https://upload.wikimedia.org/wikipedia/commons/6/68/Flag_of_Togo.svg" },
            { name: "Tonga", url: "https://www.mfa.gov.to/", flag: "https://upload.wikimedia.org/wikipedia/commons/9/9a/Flag_of_Tonga.svg" },
            { name: "Trinidad and Tobago", url: "http://www.foreign.gov.tt/", flag: "https://upload.wikimedia.org/wikipedia/commons/6/64/Flag_of_Trinidad_and_Tobago.svg" },
            { name: "Tunisia", url: "https://www.diplomatie.gov.tn/", flag: "https://upload.wikimedia.org/wikipedia/commons/c/ce/Flag_of_Tunisia.svg" },
            { name: "Turkey", url: "http://www.mfa.gov.tr/", flag: "https://upload.wikimedia.org/wikipedia/commons/b/b4/Flag_of_Turkey.svg" },
            { name: "Turkmenistan", url: "https://www.mfa.gov.tm/en/", flag: "https://upload.wikimedia.org/wikipedia/commons/1/1b/Flag_of_Turkmenistan.svg" },
            { name: "Tuvalu", url: "https://tuvalu-legation.org/", flag: "https://upload.wikimedia.org/wikipedia/commons/3/38/Flag_of_Tuvalu.svg" },
            { name: "Uganda", url: "https://www.mofa.go.ug/", flag: "https://upload.wikimedia.org/wikipedia/commons/4/4e/Flag_of_Uganda.svg" },
            { name: "Ukraine", url: "https://mfa.gov.ua/en", flag: "https://upload.wikimedia.org/wikipedia/commons/4/49/Flag_of_Ukraine.svg" },
            { name: "United Arab Emirates", url: "https://www.mofaic.gov.ae/", flag: "https://upload.wikimedia.org/wikipedia/commons/c/cb/Flag_of_the_United_Arab_Emirates.svg" },
            { name: "United Kingdom", url: "https://www.gov.uk/browse/visas-immigration", flag: "https://upload.wikimedia.org/wikipedia/en/a/ae/Flag_of_the_United_Kingdom.svg" },
            { name: "United States", url: "https://travel.state.gov/content/travel/en/international-travel.html", flag: "https://upload.wikimedia.org/wikipedia/en/a/a4/Flag_of_the_United_States.svg" },
            { name: "Uruguay", url: "https://www.gub.uy/ministerio-relaciones-exteriores/", flag: "https://upload.wikimedia.org/wikipedia/commons/f/fe/Flag_of_Uruguay.svg" },
            { name: "Uzbekistan", url: "https://mfa.uz/en/", flag: "https://upload.wikimedia.org/wikipedia/commons/8/84/Flag_of_Uzbekistan.svg" },
            { name: "Vanuatu", url: "https://foreign.gov.vu/", flag: "https://upload.wikimedia.org/wikipedia/commons/b/bc/Flag_of_Vanuatu.svg" },
            { name: "Vatican City", url: "http://www.vatican.va/", flag: "https://upload.wikimedia.org/wikipedia/commons/3/39/Flag_of_the_Vatican_City_%282023%E2%80%93present%29.svg" },
            { name: "Venezuela", url: "http://mppre.gob.ve/", flag: "https://upload.wikimedia.org/wikipedia/commons/0/06/Flag_of_Venezuela.svg" },
            { name: "Vietnam", url: "https://www.mofa.gov.vn/", flag: "https://upload.wikimedia.org/wikipedia/commons/2/21/Flag_of_Vietnam.svg" },
            { name: "Western Sahara", url: "", flag: "https://upload.wikimedia.org/wikipedia/commons/2/26/Flag_of_the_Sahrawi_Arab_Democratic_Republic.svg" },
            { name: "Yemen", url: "http://www.mofa.gov.ye/", flag: "https://upload.wikimedia.org/wikipedia/commons/8/89/Flag_of_Yemen.svg" },
            { name: "Zambia", url: "https://www.mfa.gov.zm/", flag: "https://upload.wikimedia.org/wikipedia/commons/0/06/Flag_of_Zambia.svg" },
            { name: "Zimbabwe", url: "http://www.zimfa.gov.zw/", flag: "https://upload.wikimedia.org/wikipedia/commons/6/6a/Flag_of_Zimbabwe.svg" },
     
           




            
            { name: "তানজানিয়া", url: "http://www.tanzania.go.tz", flag: "https://upload.wikimedia.org/wikipedia/commons/3/38/Flag_of_Tanzania.svg" },
            { name: "কাতার", url: "http://www.moi.gov.qa/VsaWeb/Actions?action=geteServiceVisaInfoInput&language=english", flag: "https://upload.wikimedia.org/wikipedia/commons/6/65/Flag_of_Qatar.svg" },
            { name: "কুয়েত", url: "http://www.moi.gov.kw", flag: "https://upload.wikimedia.org/wikipedia/commons/a/aa/Flag_of_Kuwait.svg" },
            { name: "পাকিস্তান", url: "http://www.moitt.gov.pk/", flag: "https://upload.wikimedia.org/wikipedia/commons/3/32/Flag_of_Pakistan.svg" },
            { name: "সৌদি আরব", url: "http://www.moi.gov.sa/", flag: "https://upload.wikimedia.org/wikipedia/commons/0/0d/Flag_of_Saudi_Arabia.svg" },
            { name: "দুবাই/আরব আমিরাত", url: "http://www.moi.gov.ae", flag: "https://upload.wikimedia.org/wikipedia/commons/c/cb/Flag_of_the_United_Arab_Emirates.svg" },
            { name: "মিশর", url: "http://www.moiegypt.gov.eg/english/", flag: "https://upload.wikimedia.org/wikipedia/commons/f/fe/Flag_of_Egypt.svg" },
            { name: "বাংলাদেশ", url: "http://www.moi.gov.bd", flag: "https://upload.wikimedia.org/wikipedia/commons/f/f9/Flag_of_Bangladesh.svg" },
            { name: "সাইপ্রাস", url: "http://moi.gov.cy/", flag: "https://upload.wikimedia.org/wikipedia/commons/d/d4/Flag_of_Cyprus.svg" },
            { name: "নেপাল", url: "http://www.moic.gov.np/", flag: "https://upload.wikimedia.org/wikipedia/commons/9/9b/Flag_of_Nepal.svg" },
            { name: "আলবেনিয়া", url: "http://www.moi.gov.al/", flag: "https://upload.wikimedia.org/wikipedia/commons/3/36/Flag_of_Albania.svg" },
            { name: "জাম্বিয়া", url: "http://www.moi.gov.gm/", flag: "https://upload.wikimedia.org/wikipedia/commons/0/06/Flag_of_Zambia.svg" },
            { name: "জর্দান", url: "http://www.moi.gov.jo/", flag: "https://upload.wikimedia.org/wikipedia/commons/c/c0/Flag_of_Jordan.svg" },
            { name: "ইন্ডিয়া", url: "http://labour.nic.in/", flag: "https://upload.wikimedia.org/wikipedia/en/4/41/Flag_of_India.svg" },
            { name: "কেনিয়া", url: "http://www.labour.go.ke/", flag: "https://upload.wikimedia.org/wikipedia/commons/4/49/Flag_of_Kenya.svg" },
            { name: "ইটালী", url: "https://www.visaservices.org.in/Italy-Bangladesh-Tracking/", flag: "https://upload.wikimedia.org/wikipedia/en/0/03/Flag_of_Italy.svg" },
            { name: "সিংগাপুর", url: "http://www.mom.gov.sg/", flag: "https://upload.wikimedia.org/wikipedia/commons/4/48/Flag_of_Singapore.svg" },
            { name: "গ্রীস", url: "http://www.mddsz.gov.si/en", flag: "https://upload.wikimedia.org/wikipedia/commons/5/5c/Flag_of_Greece.svg" },
            { name: "শ্রীলংকা", url: "http://www.labourdept.gov.lk/", flag: "https://upload.wikimedia.org/wikipedia/commons/1/11/Flag_of_Sri_Lanka.svg" },
            { name: "দক্ষিণ আফ্রিকা", url: "http://www.labour.gov.za/", flag: "https://upload.wikimedia.org/wikipedia/commons/a/af/Flag_of_South_Africa.svg" },
            { name: "ইরান", url: "http://www.irimlsa.ir/en", flag: "https://upload.wikimedia.org/wikipedia/commons/c/ca/Flag_of_Iran.svg" },
            { name: "ঘানা", url: "http://www.ghana.gov.gh/", flag: "https://upload.wikimedia.org/wikipedia/commons/1/19/Flag_of_Ghana.svg" },
            { name: "থাইল্যান্ড", url: "http://www.mfa.go.th", flag: "https://upload.wikimedia.org/wikipedia/commons/a/a9/Flag_of_Thailand.svg" },
            { name: "বাহরাইন", url: "http://www.mol.gov.bh", flag: "https://upload.wikimedia.org/wikipedia/commons/2/2c/Flag_of_Bahrain.svg" },
            { name: "ভূটান", url: "http://www.molhr.gov.bt/", flag: "https://upload.wikimedia.org/wikipedia/commons/9/91/Flag_of_Bhutan.svg" },
            { name: "কলম্বিয়া", url: "http://www.labour.gov.bc.ca/esb/", flag: "https://upload.wikimedia.org/wikipedia/commons/2/21/Flag_of_Colombia.svg" },
            { name: "কানাডা", url: "http://www.labour.gov.on.ca/english/", flag: "https://upload.wikimedia.org/wikipedia/commons/d/d9/Flag_of_Canada_%28Pantone%29.svg" },
            { name: "বারবাডোস", url: "http://www.labour.gov.bb/", flag: "https://upload.wikimedia.org/wikipedia/commons/e/ef/Flag_of_Barbados.svg" },
            { name: "কোরিয়া", url: "http://www.moel.go.kr/english", flag: "https://upload.wikimedia.org/wikipedia/commons/0/09/Flag_of_South_Korea.svg" },
            { name: "জাপান", url: "http://www.mhlw.go.jp/english/", flag: "https://upload.wikimedia.org/wikipedia/en/9/9e/Flag_of_Japan.svg" },
            { name: "সাইপ্রাস", url: "http://www.mfa.gov.cy/", flag: "https://upload.wikimedia.org/wikipedia/commons/d/d4/Flag_of_Cyprus.svg" },
            { name: "ভিয়েতনাম", url: "http://english.molisa.gov.vn/", flag: "https://upload.wikimedia.org/wikipedia/commons/2/21/Flag_of_Vietnam.svg" },
            { name: "নিউজিল্যান্ড", url: "http://www.dol.govt.nz/", flag: "https://upload.wikimedia.org/wikipedia/commons/3/3e/Flag_of_New_Zealand.svg" },
            { name: "নামিবিয়া", url: "http://www.mol.gov.na/", flag: "https://upload.wikimedia.org/wikipedia/commons/0/00/Flag_of_Namibia.svg" },
            { name: "মালদ্বীপ", url: "http://mhrys.gov.mv/", flag: "https://upload.wikimedia.org/wikipedia/commons/0/0f/Flag_of_Maldives.svg" },
            { name: "মিয়ানমার", url: "http://www.mol.gov.mm/", flag: "https://upload.wikimedia.org/wikipedia/commons/8/8c/Flag_of_Myanmar.svg" },
            { name: "লেবানন", url: "http://www.labor.gov.lb/", flag: "https://upload.wikimedia.org/wikipedia/commons/5/59/Flag_of_Lebanon.svg" },
            { name: "পোল্যান্ড", url: "http://www.mpips.gov.pl/en", flag: "https://upload.wikimedia.org/wikipedia/en/1/12/Flag_of_Poland.svg" },
            { name: "ইংল্যান্ড", url: "http://www.ukba.homeoffice.gov.uk", flag: "https://upload.wikimedia.org/wikipedia/en/a/ae/Flag_of_the_United_Kingdom.svg" },
            { name: "বুলগেরিয়া", url: "http://www.mlsp.government.bg/en", flag: "https://upload.wikimedia.org/wikipedia/commons/9/9a/Flag_of_Bulgaria.svg" },
            { name: "আমেরিকা", url: "http://www.dvlottery.state.gov/ESC", flag: "https://upload.wikimedia.org/wikipedia/en/a/a4/Flag_of_the_United_States.svg" },
            { name: "স্পেন", url: "http://www.mtin.e", flag: "https://upload.wikimedia.org/wikipedia/en/9/9a/Flag_of_Spain.svg" }
        ];

        const countryList = document.getElementById('country-list');

        countries.forEach(country => {
            const countryCard = document.createElement('div');
            countryCard.className = 'col-md-4 country-card';
            countryCard.innerHTML = `
                <div class="card text-center">
                    <div class="card-body">
                        <img src="${country.flag}" alt="${country.name} Flag" class="country-flag">
                        <h5 class="card-title">
                            ${country.name}
                        </h5>
                        <a href="${country.url}" target="_blank" class="btn btn-primary">Check Visa</a>
                    </div>
                </div>
            `;
            countryList.appendChild(countryCard);
        });
